name: maldi
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.51.0=h9a5124b_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.5.4=h5503f6c_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.19=hcd7f573_2_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - aiobotocore==2.25.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aioitertools==0.13.0
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - anndata==0.11.4
      - annotated-types==0.7.0
      - app-model==0.4.0
      - appdirs==1.4.4
      - appnope==0.1.4
      - array-api-compat==1.12.0
      - asciitree==0.3.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - botocore==1.40.61
      - build==1.3.0
      - cachey==0.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.2
      - colorcet==3.1.0
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - dask==2024.11.2
      - dask-expr==1.1.19
      - dask-image==2024.5.3
      - datashader==0.18.2
      - debugpy==1.8.17
      - decorator==5.2.1
      - distributed==2024.11.2
      - docrep==0.3.2
      - docstring-parser==0.17.0
      - docutils==0.21.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fasteners==0.20
      - flexcache==0.3
      - flexparser==0.4
      - flowio==1.4.0
      - fonttools==4.60.1
      - freetype-py==2.5.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - geopandas==1.1.1
      - goatpy==0.0.1
      - h5py==3.15.1
      - heapdict==1.0.1
      - hsluv==5.0.4
      - idna==3.11
      - igraph==1.0.0
      - imagecodecs==2025.3.30
      - imageio==2.37.2
      - imagesize==1.4.1
      - importlib-metadata==8.7.0
      - in-n-out==0.2.1
      - inflect==7.5.0
      - ipykernel==6.31.0
      - ipython==8.37.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - legacy-api-wrap==1.5
      - leidenalg==0.11.0
      - llvmlite==0.45.1
      - locket==1.0.0
      - loguru==0.7.3
      - magicgui==0.10.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - matplotlib-scalebar==0.9.0
      - mdurl==0.1.2
      - metaspace-converter==1.1.1
      - metaspace2020==2.0.9
      - more-itertools==10.8.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multipledispatch==1.0.0
      - multiscale-spatial-image==2.0.3
      - napari==0.6.6
      - napari-console==0.1.4
      - napari-matplotlib==3.0.1
      - napari-plugin-engine==0.2.0
      - napari-spatialdata==0.6.0
      - napari-svg==0.2.1
      - narwhals==2.12.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - npe2==0.7.9
      - numba==0.62.1
      - numcodecs==0.13.1
      - numpy==2.2.6
      - numpydoc==1.9.0
      - ome-types==0.6.2
      - ome-zarr==0.11.1
      - omnipath==1.0.12
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - param==2.2.1
      - parso==0.8.5
      - partd==1.4.2
      - patsy==1.0.2
      - pexpect==4.9.0
      - pillow==12.0.0
      - pims==0.7
      - pint==0.24.4
      - platformdirs==4.5.0
      - plotly==6.5.0
      - pooch==1.8.2
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.3
      - psygnal==0.15.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pyconify==0.2.1
      - pyct==0.6.0
      - pydantic==2.12.4
      - pydantic-compat==0.1.2
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pygments==2.19.2
      - pyimzml==1.5.5
      - pynndescent==0.5.13
      - pyogrio==0.11.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pyproj==3.7.1
      - pyproject-hooks==1.2.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.18
      - pyqt5-sip==12.17.1
      - pyqtgraph==0.13.7
      - python-dateutil==2.9.0.post0
      - python-igraph==1.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qtconsole==5.7.0
      - qtpy==2.4.3
      - readfcs==2.0.1
      - referencing==0.37.0
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.28.0
      - s3fs==2025.10.0
      - scanpy==1.11.5
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - session-info2==0.2.3
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - slicerator==1.1.0
      - snowballstemmer==3.0.1
      - sopa==2.1.8
      - sortedcontainers==2.4.0
      - spatial-image==1.2.3
      - spatialdata==0.5.0
      - spatialdata-io==0.3.0
      - spatialdata-plot==0.2.12
      - sphinx==8.1.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - squidpy==1.6.5
      - stack-data==0.6.3
      - statsmodels==0.14.5
      - superqt==0.7.6
      - tblib==3.2.1
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tinycss2==1.4.0
      - tomli==2.3.0
      - tomli-w==1.2.0
      - toolz==1.1.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typeguard==4.4.4
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - validators==0.35.0
      - vispy==0.15.2
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - wheezy-template==3.2.3
      - wrapt==1.17.3
      - xarray==2025.6.1
      - xarray-dataclass==3.0.0
      - xarray-datatree==0.0.14
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - xsdata==25.7
      - yarl==1.22.0
      - zarr==2.18.3
      - zict==3.0.0
      - zipp==3.23.0
prefix: /Users/andrewcauser/anaconda3/envs/maldi
